---
title: "viash test"
description: ""
lead: ""
date: 2021-05-28T14:00:00+00:00
lastmod: "`r format(Sys.time(), '%Y-%Om-%dT%H:%M:%S+00:00')`"
draft: false
images: []
menu:
  docs:
    parent: "reference_commands"
weight: 420
toc: true
---


```{r setup, include=FALSE}
library(tidyverse)

knitr::opts_chunk$set(echo = FALSE)

# get info from help page
out <- processx::run("viash", c("test", "-h"))
txt <- out$stdout %>% strsplit("\n") %>% first()

detect_links <- function(x) {
  x %>% 
    gsub("viash[ \n]*config", "[viash config](/docs/reference_config/config)", .) %>% 
    gsub("config[ \n]*mods", "[config mods](/docs/reference_config/config_mods/)", .)
}
```

```{r desc}
desc <- txt[seq(
  2,
  grep("^Usage:", txt)-2
)] %>% gsub("^viash ", "# viash ", .) %>% 
  paste(., collapse = "\n") %>% 
  detect_links
knitr::asis_output(desc)
```

Usage: 
```{r usage}
usage <- txt[seq(
  grep("^Usage:", txt)+1,
  grep("^Arguments:", txt)-2
)] %>% 
  {paste0("```bash\n", paste(., collapse = "\n"), "\n```\n")} %>% 
  detect_links
knitr::asis_output(usage)
```

Arguments:

* `config`: A viash config file (example: `config.vsh.yaml`). This
            argument can also be a script with the config as a
            header.
```{r arg}
trail <- grep("^ trailing arguments:", txt)
if (length(trail) == 0) trail <- length(txt)+1
arg <- txt[seq(
  grep("^Arguments:", txt)+1,
  trail-1
)] %>% 
  gsub("^  (-[^A-Z]*)", "* `\\1`: ", .) %>% 
  gsub(" *$", "", .) %>% 
  paste(., collapse = "\n") %>% 
  detect_links
knitr::asis_output(arg)
```
